name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Typecheck with TypeScript
        run: npm run type-check

      - name: Lint with ESLint
        run: npm run lint

      - name: Print Enviroment Variable
        run: echo $MY_ENV_VAR